# Generated by Django 5.2.6 on 2025-09-22 06:26

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobblogpost',
            name='blog_detail',
            field=django_ckeditor_5.fields.CKEditor5Field(default='No description provided.', help_text='Detailed description of the blog'),
        ),
    ]
