# Generated by Django 5.2.6 on 2025-09-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_jobblogpost_blog_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobblogpost',
            name='popular_post',
            field=models.BooleanField(default=False),
        ),
    ]
