# Generated by Django 5.2.6 on 2025-09-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_jobblogpost_popular_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobblogpost',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
